
coffed : coffed.c 
	gcc -g -DDEBUG list.c string_view.c logger.c log.c command_history.c log_view_header.c log_view.c log_window.c message_window.c command_window.c main_panel.c coffed.c -lncurses -lm -o ../target/coffed

