
coffed : coffed.c 
	$(CC) -g -DDEBUG list.c string_view.c logger.c log.c command_history.c log_view_header.c log_view.c log_window.c message_window.c command_window.c file_list_view.c main_panel.c coffed.c -lpanelw -lncursesw -lm -o ../target/coffed

