
coffed : coffed.c 
	$(CC) -ggdb -DDEBUG list.c string_view.c logger.c log.c log_view_header.c log_view.c log_window.c message_window.c rl_command_window.c file_list_view.c main_panel.c coffed.c -lpanelw -lncursesw -lreadline -lm -o ../target/coffed

